[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/workbench && bun run build"]

[start]
cmd = "cd apps/workbench && bun run start"
