{{- if not .Values.objectStore.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attest.fullname" . }}-object-store
  labels:
    {{- include "attest.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ default "minioadmin" .Values.objectStore.accessKey | quote }}
  secret-key: {{ default "minioadmin" .Values.objectStore.secretKey | quote }}
  signing-key: {{ .Values.signingKey | quote }}
{{- end }}
